services:
  mysql:
    container_name: my-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: caterest
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
  caterest:
    container_name: caterest_service
    image: davidcodin/caterest:1.0.0
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      mysql:
          condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/caterest
networks:
  my-network:
    driver: bridge

